<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '8',
    'typeid' => '0',
    'title' => 'jghfhgfghf',
    'style' => '',
    'thumb' => '',
    'keywords' => 'jghfhgfghf',
    'description' => 'fhgfhgfghfghfghfghfghfhgf',
    'posids' => '0',
    'url' => 'http://local.phpcms.com/index.php?m=content&c=index&a=show&catid=8&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1385897056',
    'updatetime' => '1385897074',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '8',
    'typeid' => '0',
    'title' => 'hgfhgfhgf',
    'style' => '',
    'thumb' => '',
    'keywords' => 'hgfhgfhgf',
    'description' => 'ghfvhgfhgfhg',
    'posids' => '0',
    'url' => 'http://local.phpcms.com/index.php?m=content&c=index&a=show&catid=8&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1385897229',
    'updatetime' => '1385897245',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>